// Code generated by protoc-gen-go-http. DO NOT EDIT.

package v1

import (
	context "context"
	http1 "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	mux "github.com/gorilla/mux"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(http.Request)
var _ = new(context.Context)
var _ = binding.MapProto
var _ = mux.NewRouter

const _ = http1.SupportPackageIsVersion1

type GreeterHandler interface {
	AnyJson(context.Context, *HelloStructRequest) (*HelloStructResponse, error)

	AnyTypes(context.Context, *HelloAnyTypesRequest) (*HelloAnyTypesResponse, error)

	FiledMask(context.Context, *HelloFieldMaskRequest) (*HelloFieldMaskResponse, error)

	IsDefault(context.Context, *HelloIsDefaultRequest) (*HelloDefaultReply, error)

	SayEmpty(context.Context, *emptypb.Empty) (*HelloReply, error)

	SayHello(context.Context, *HelloRequest) (*HelloReply, error)

	Times(context.Context, *HelloTsRequest) (*HelloTsResponse, error)
}

func NewGreeterHandler(srv GreeterHandler, opts ...http1.HandleOption) http.Handler {
	h := http1.DefaultHandleOptions()
	for _, o := range opts {
		o(&h)
	}
	r := mux.NewRouter()

	r.HandleFunc("/helloworld/{name}", func(w http.ResponseWriter, r *http.Request) {
		var in HelloRequest
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		if err := binding.BindVars(mux.Vars(r), &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*HelloRequest))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/hello/sayEmpty", func(w http.ResponseWriter, r *http.Request) {
		var in emptypb.Empty
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayEmpty(ctx, req.(*emptypb.Empty))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/hello/isDefault", func(w http.ResponseWriter, r *http.Request) {
		var in HelloIsDefaultRequest
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.IsDefault(ctx, req.(*HelloIsDefaultRequest))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloDefaultReply)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("GET")

	r.HandleFunc("/hello/fieldMask", func(w http.ResponseWriter, r *http.Request) {
		var in HelloFieldMaskRequest
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.FiledMask(ctx, req.(*HelloFieldMaskRequest))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloFieldMaskResponse)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/hello/any", func(w http.ResponseWriter, r *http.Request) {
		var in HelloAnyTypesRequest
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AnyTypes(ctx, req.(*HelloAnyTypesRequest))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloAnyTypesResponse)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/hello/ts", func(w http.ResponseWriter, r *http.Request) {
		var in HelloTsRequest
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Times(ctx, req.(*HelloTsRequest))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloTsResponse)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	r.HandleFunc("/hello/struct", func(w http.ResponseWriter, r *http.Request) {
		var in HelloStructRequest
		if err := h.Decode(r, &in); err != nil {
			h.Error(w, r, err)
			return
		}

		next := func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AnyJson(ctx, req.(*HelloStructRequest))
		}
		if h.Middleware != nil {
			next = h.Middleware(next)
		}
		out, err := next(r.Context(), &in)
		if err != nil {
			h.Error(w, r, err)
			return
		}
		reply := out.(*HelloStructResponse)
		if err := h.Encode(w, r, reply); err != nil {
			h.Error(w, r, err)
		}
	}).Methods("POST")

	return r
}

type GreeterHTTPClient interface {
	AnyJson(ctx context.Context, req *HelloStructRequest, opts ...http1.CallOption) (rsp *HelloStructResponse, err error)

	AnyTypes(ctx context.Context, req *HelloAnyTypesRequest, opts ...http1.CallOption) (rsp *HelloAnyTypesResponse, err error)

	FiledMask(ctx context.Context, req *HelloFieldMaskRequest, opts ...http1.CallOption) (rsp *HelloFieldMaskResponse, err error)

	IsDefault(ctx context.Context, req *HelloIsDefaultRequest, opts ...http1.CallOption) (rsp *HelloDefaultReply, err error)

	SayEmpty(ctx context.Context, req *emptypb.Empty, opts ...http1.CallOption) (rsp *HelloReply, err error)

	SayHello(ctx context.Context, req *HelloRequest, opts ...http1.CallOption) (rsp *HelloReply, err error)

	Times(ctx context.Context, req *HelloTsRequest, opts ...http1.CallOption) (rsp *HelloTsResponse, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http1.Client
}

func NewGreeterHTTPClient(client *http1.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

func (c *GreeterHTTPClientImpl) AnyJson(ctx context.Context, in *HelloStructRequest, opts ...http1.CallOption) (out *HelloStructResponse, err error) {
	path := binding.EncodePath("POST", "/hello/struct", in)
	out = &HelloStructResponse{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/hello/struct"))

	return
}

func (c *GreeterHTTPClientImpl) AnyTypes(ctx context.Context, in *HelloAnyTypesRequest, opts ...http1.CallOption) (out *HelloAnyTypesResponse, err error) {
	path := binding.EncodePath("POST", "/hello/any", in)
	out = &HelloAnyTypesResponse{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/hello/any"))

	return
}

func (c *GreeterHTTPClientImpl) FiledMask(ctx context.Context, in *HelloFieldMaskRequest, opts ...http1.CallOption) (out *HelloFieldMaskResponse, err error) {
	path := binding.EncodePath("POST", "/hello/fieldMask", in)
	out = &HelloFieldMaskResponse{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/hello/fieldMask"))

	return
}

func (c *GreeterHTTPClientImpl) IsDefault(ctx context.Context, in *HelloIsDefaultRequest, opts ...http1.CallOption) (out *HelloDefaultReply, err error) {
	path := binding.EncodePath("GET", "/hello/isDefault", in)
	out = &HelloDefaultReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("GET"), http1.PathPattern("/hello/isDefault"))

	return
}

func (c *GreeterHTTPClientImpl) SayEmpty(ctx context.Context, in *emptypb.Empty, opts ...http1.CallOption) (out *HelloReply, err error) {
	path := binding.EncodePath("GET", "/hello/sayEmpty", in)
	out = &HelloReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("GET"), http1.PathPattern("/hello/sayEmpty"))

	return
}

func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http1.CallOption) (out *HelloReply, err error) {
	path := binding.EncodePath("GET", "/helloworld/{name}", in)
	out = &HelloReply{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("GET"), http1.PathPattern("/helloworld/{name}"))

	return
}

func (c *GreeterHTTPClientImpl) Times(ctx context.Context, in *HelloTsRequest, opts ...http1.CallOption) (out *HelloTsResponse, err error) {
	path := binding.EncodePath("POST", "/hello/ts", in)
	out = &HelloTsResponse{}

	err = c.cc.Invoke(ctx, path, nil, &out, http1.Method("POST"), http1.PathPattern("/hello/ts"))

	return
}
